# Generated by Django 4.2.6 on 2023-10-18 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Nombre')),
                ('cod', models.CharField(max_length=3, verbose_name='Código')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ape', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('user', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Nombre')),
                ('cod', models.IntegerField(max_length=9, verbose_name='Código')),
                ('des', models.TextField(verbose_name='Descripción')),
                ('pvp', models.IntegerField(max_length=20, verbose_name='Precio')),
                ('enc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.sede')),
            ],
            options={
                'verbose_name_plural': 'Artículos',
            },
        ),
    ]
