# Generated by Django 4.2.6 on 2023-10-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='cod',
            field=models.CharField(max_length=9, verbose_name='Código'),
        ),
    ]
