# Generated by Django 4.2.6 on 2023-10-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_articulo_cod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='pvp',
            field=models.IntegerField(verbose_name='Precio'),
        ),
    ]
