# Generated by Django 4.2.6 on 2023-10-18 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_articulo_pvp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='enc',
            new_name='sede',
        ),
    ]
