# Generated by Django 4.2.6 on 2023-11-21 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_proveedores_cod'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.proveedores'),
        ),
    ]
