# Generated by Django 4.2.6 on 2023-11-21 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_articulo_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='fecha_stock',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de Stock'),
        ),
    ]
